### ISSUE TITLE
installation error at first attempt

### ISSUE THREAD

**Issue by Immortalem** [Javex/fluxscoreboard#16]
Traceback (most recent call last):
  File "./run", line 367, in <module>
    function(**args)
  File "./run", line 190, in install
    settings = _load_configuration(cfg_path)
  File "./run", line 107, in _load_configuration
    import paste.deploy.loadwsgi  # import here because not installed before
ImportError: No module named paste.deploy.loadwsgi

running ./run install production a second time works fine

**Comment by Immortalem** [comment]
first look leads to the conclusion, that the environment isn't properly updated at that point. 

The second execution of the script does not install anything.
